import { useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";
import {
  ArrowLeft, ArrowUpLeft, BookOpen, Bookmark, Bot, CalendarDays, Check, ChevronDown, Clock3,
  Heart, Library, Menu, MessageCircle, Moon, Search, Send, ShoppingBag, Sparkles, Star,
  Tag, TrendingUp, UserRound, WandSparkles, X, Zap,
} from "lucide-react";

type Book = { id: number; title: string; author: string; category: string; price: string; oldPrice: string; rating: string; reviews: string; badge: string; cover: string; accent: string; format: string; description: string };

const books: Book[] = [
  { id: 1, title: "فن اللامبالاة الذكية", author: "سارة العتيبي", category: "تطوير الذات", price: "39 ر.س", oldPrice: "59 ر.س", rating: "4.9", reviews: "128", badge: "الأكثر مبيعًا", cover: "فن اللامبالاة", accent: "coral", format: "ورقي + رقمي", description: "دليل عملي هادئ يساعدك على ترتيب أولوياتك وصناعة حياة أكثر وضوحًا واتزانًا." },
  { id: 2, title: "ابدأ مشروعك الآن", author: "خالد المنصور", category: "الأعمال", price: "49 ر.س", oldPrice: "75 ر.س", rating: "4.8", reviews: "96", badge: "خصم 35%", cover: "ابدأ مشروعك", accent: "navy", format: "رقمي", description: "من الفكرة إلى أول عميل: خطوات عملية لبناء مشروع صغير قابل للنمو." },
  { id: 3, title: "الذكاء الاصطناعي ببساطة", author: "د. مريم حجازي", category: "الذكاء الاصطناعي", price: "55 ر.س", oldPrice: "65 ر.س", rating: "4.9", reviews: "74", badge: "جديد", cover: "AI ببساطة", accent: "violet", format: "ورقي + رقمي", description: "مدخل عربي ممتع لفهم الذكاء الاصطناعي وأدواته واستخداماته اليومية." },
  { id: 4, title: "مدن لا تنام", author: "ليان الحربي", category: "الروايات", price: "32 ر.س", oldPrice: "42 ر.س", rating: "4.7", reviews: "211", badge: "اختيار القراء", cover: "مدن لا تنام", accent: "teal", format: "ورقي", description: "رواية إنسانية عن أحلام صغيرة تكبر في مدينة واسعة لا تعرف السكون." },
  { id: 5, title: "البرمجة من الصفر", author: "عمر الشمري", category: "البرمجة", price: "62 ر.س", oldPrice: "80 ر.س", rating: "4.8", reviews: "63", badge: "الأكثر طلبًا", cover: "البرمجة", accent: "gold", format: "رقمي", description: "تعلم التفكير البرمجي وابنِ أول تطبيق لك بأسلوب مبسط ومنظم." },
  { id: 6, title: "اقتصاد المستقبل", author: "نواف القحطاني", category: "الاقتصاد", price: "44 ر.س", oldPrice: "55 ر.س", rating: "4.6", reviews: "42", badge: "ترشيحنا", cover: "اقتصاد المستقبل", accent: "plum", format: "ورقي + رقمي", description: "قراءة واضحة للتحولات الاقتصادية التي ستصنع سوق العمل في السنوات القادمة." },
];

const categories: { name: string; icon: LucideIcon; tone: string }[] = [
  { name: "الروايات", icon: BookOpen, tone: "peach" }, { name: "تطوير الذات", icon: Sparkles, tone: "mint" }, { name: "الأعمال", icon: TrendingUp, tone: "blue" }, { name: "التقنية", icon: Zap, tone: "violet" }, { name: "الذكاء الاصطناعي", icon: Bot, tone: "cyan" }, { name: "البرمجة", icon: WandSparkles, tone: "gold" }, { name: "التاريخ", icon: CalendarDays, tone: "rose" }, { name: "الأطفال", icon: Heart, tone: "lavender" }];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("الكل");
  const [favorites, setFavorites] = useState<number[]>([]);
  const [cart, setCart] = useState<Book[]>([]);
  const [selected, setSelected] = useState<Book | null>(null);
  const [cartOpen, setCartOpen] = useState(false);
  const [assistantOpen, setAssistantOpen] = useState(false);
  const [querySent, setQuerySent] = useState(false);

  const filteredBooks = useMemo(() => books.filter((book) => {
    const matchesCategory = activeCategory === "الكل" || book.category === activeCategory;
    const q = search.trim().toLowerCase();
    return matchesCategory && (!q || `${book.title} ${book.author} ${book.category}`.toLowerCase().includes(q));
  }), [activeCategory, search]);

  const toggleFavorite = (id: number) => setFavorites((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const addToCart = (book: Book) => { setCart((items) => items.some((item) => item.id === book.id) ? items : [...items, book]); setCartOpen(true); };
  const goTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };

  return <main className="bookstore" dir="rtl">
    <div className="announcement"><span><Sparkles size={14} /> شحن مجاني للطلبات فوق 150 ر.س</span><span className="announcement-link">اكتشف عروض الأسبوع <ArrowLeft size={14} /></span></div>
    <header className="site-header"><div className="header-inner">
      <a className="book-logo" href="#top"><span className="logo-mark"><BookOpen size={21} /></span><span><strong>رفوف</strong><small>متجر الكتب الذكي</small></span></a>
      <nav className={`main-nav ${menuOpen ? "open" : ""}`}><a href="#top" onClick={() => setMenuOpen(false)}>الرئيسية</a><a href="#books" onClick={() => setMenuOpen(false)}>الكتب</a><a href="#categories" onClick={() => setMenuOpen(false)}>التصنيفات</a><a href="#bestsellers" onClick={() => setMenuOpen(false)}>الأكثر مبيعًا</a><a href="#offers" onClick={() => setMenuOpen(false)}>العروض</a><a href="#authors" onClick={() => setMenuOpen(false)}>المؤلفون</a></nav>
      <div className="header-actions"><button className="header-icon mobile-only" onClick={() => setMenuOpen(!menuOpen)} aria-label="القائمة">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><button className="header-icon" onClick={() => setFavorites([])} aria-label="المفضلة"><Heart size={19} />{favorites.length > 0 && <b>{favorites.length}</b>}</button><button className="header-icon" onClick={() => setCartOpen(true)} aria-label="السلة"><ShoppingBag size={19} />{cart.length > 0 && <b>{cart.length}</b>}</button><button className="login-button"><UserRound size={16} /> دخول</button></div>
    </div><div className="search-wrap"><Search size={19} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث عن كتاب، مؤلف، أو موضوع..." /><kbd>⌘ K</kbd></div></header>

    <section className="hero-bookstore" id="top"><div className="hero-content"><span className="eyebrow"><span className="eyebrow-dot" /> أكثر من 10,000 عنوان بين يديك</span><h1>اكتشف كتابك<br /><em>القادم.</em></h1><p>رفوفك تبدأ من هنا. مجموعة مختارة من الكتب التي تلهمك، تطورك، وتبقى معك في كل فصل من فصول الحياة.</p><div className="hero-actions"><button className="btn-primary" onClick={() => goTo("books")}>تصفح الكتب <ArrowLeft size={17} /></button><button className="btn-ghost" onClick={() => goTo("bestsellers")}><TrendingUp size={17} /> الأكثر مبيعًا</button></div><div className="reader-trust"><div className="trust-avatars"><span>ن</span><span>س</span><span>م</span><span>+8</span></div><span><strong>+24,000</strong> قارئ وجد كتابه معنا</span></div></div><div className="hero-books" aria-label="أغلفة كتب مميزة"><div className="hero-sparkle sparkle-one">✦</div><div className="hero-sparkle sparkle-two">✦</div><BookCover book={books[1]} size="small" className="floating-book left-book" /><BookCover book={books[0]} size="large" className="main-book" /><BookCover book={books[2]} size="small" className="floating-book right-book" /><div className="hero-glow" /></div></section>

    <section className="category-section section-width" id="categories"><div className="section-title"><div><span className="section-label">استكشف حسب اهتمامك</span><h2>كل فكرة لها <em>رف.</em></h2></div><button className="link-button">عرض كل التصنيفات <ArrowLeft size={15} /></button></div><div className="category-grid">{categories.map(({ name, icon: Icon, tone }) => <button className="category-card" key={name} onClick={() => { setActiveCategory(name === "التقنية" ? "الكل" : name); goTo("books"); }}><span className={`category-icon ${tone}`}><Icon size={22} /></span><strong>{name}</strong><small>{books.filter((book) => book.category === name || (name === "التقنية" && book.category === "البرمجة")).length + 12} كتاب</small></button>)}</div></section>

    <section className="books-section section-width" id="books"><div className="section-title"><div><span className="section-label">مختارات رفوف</span><h2>كتب مختارة <em>لك.</em></h2></div><button className="link-button">عرض جميع الكتب <ArrowLeft size={15} /></button></div><div className="book-toolbar"><div className="book-tabs"><button className={activeCategory === "الكل" ? "active" : ""} onClick={() => setActiveCategory("الكل")}>الكل</button>{["الروايات", "تطوير الذات", "الأعمال", "البرمجة"].map((cat) => <button key={cat} className={activeCategory === cat ? "active" : ""} onClick={() => setActiveCategory(cat)}>{cat}</button>)}</div><button className="sort-button">الأكثر شيوعًا <ChevronDown size={15} /></button></div><div className="books-grid">{filteredBooks.map((book) => <BookCard key={book.id} book={book} favorite={favorites.includes(book.id)} onFavorite={() => toggleFavorite(book.id)} onCart={() => addToCart(book)} onOpen={() => setSelected(book)} />)}</div></section>

    <section className="bestseller-section section-width" id="bestsellers"><div className="section-title light-title"><div><span className="section-label">الكتب التي يتحدث عنها الجميع</span><h2>الأكثر مبيعًا <span className="fire-mark">✦</span></h2></div><button className="light-link">تصفح القائمة <ArrowLeft size={15} /></button></div><div className="ranking-list">{books.slice(0, 3).map((book, i) => <div className="ranking-card" key={book.id}><span className="rank-number">0{i + 1}</span><BookCover book={book} size="tiny" /><div className="rank-info"><strong>{book.title}</strong><small>{book.author}</small><span><Star size={13} fill="currentColor" /> {book.rating} <i>({book.reviews})</i></span></div><button className="rank-arrow" onClick={() => setSelected(book)}><ArrowUpLeft size={17} /></button></div>)}</div></section>

    <section className="offer-banner section-width" id="offers"><div className="offer-copy"><span className="offer-label"><Tag size={14} /> عرض لفترة محدودة</span><h2>خصومات تصل إلى <em>50%</em></h2><p>اجعل هذا الأسبوع بداية لقراءة جديدة. عروض مختارة على كتب تستحق مكانًا في رفوفك.</p><div className="countdown"><div><b>02</b><small>يوم</small></div><span>:</span><div><b>14</b><small>ساعة</small></div><span>:</span><div><b>36</b><small>دقيقة</small></div></div><button className="offer-button" onClick={() => goTo("books")}>اكتشف العروض <ArrowLeft size={16} /></button></div><div className="offer-art"><BookCover book={books[3]} size="small" className="offer-book back" /><BookCover book={books[4]} size="small" className="offer-book front" /><span className="offer-burst">50%<small>خصم</small></span></div></section>

    <section className="smart-section section-width" id="authors"><div className="smart-icon"><Bot size={28} /></div><div><span className="section-label">رفيقك الذكي</span><h2>لست متأكدًا ماذا تقرأ؟</h2><p>أخبرنا بما تبحث عنه، وسيساعدك مساعد رفوف الذكي في العثور على كتاب يناسبك.</p></div><button className="btn-primary" onClick={() => setAssistantOpen(true)}>اسأل مساعد الكتب <MessageCircle size={17} /></button></section>

    <footer className="site-footer"><div className="footer-main section-width"><div className="footer-brand"><a className="book-logo" href="#top"><span className="logo-mark"><BookOpen size={21} /></span><span><strong>رفوف</strong><small>متجر الكتب الذكي</small></span></a><p>مساحة تجمعك بالكتب التي تصنع فرقًا حقيقيًا.</p></div><div><h4>المتجر</h4><a href="#books">كل الكتب</a><a href="#bestsellers">الأكثر مبيعًا</a><a href="#offers">العروض</a></div><div><h4>خدمة العملاء</h4><a href="#top">تواصل معنا</a><a href="#top">الأسئلة الشائعة</a><a href="#top">سياسة الاسترجاع</a></div><div className="newsletter"><h4>كن أول من يعرف</h4><p>اشترك لتصلك ترشيحاتنا وعروضنا.</p><div><input placeholder="بريدك الإلكتروني" /><button aria-label="اشتراك"><ArrowLeft size={16} /></button></div></div></div><div className="footer-bottom section-width"><span>© 2026 رفوف. جميع الحقوق محفوظة.</span><span>صُنع بحب للقراء <Heart size={13} fill="currentColor" /></span></div></footer>

    {selected && <div className="overlay" onClick={() => setSelected(null)}><div className="details-modal" onClick={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)}><X size={19} /></button><BookCover book={selected} size="medium" /><div className="modal-details"><span className="book-badge">{selected.badge}</span><h2>{selected.title}</h2><p className="modal-author">بقلم {selected.author}</p><p>{selected.description}</p><div className="rating"><Star size={15} fill="currentColor" /> {selected.rating} <span>({selected.reviews} تقييم)</span></div><div className="modal-price"><strong>{selected.price}</strong><del>{selected.oldPrice}</del></div><button className="btn-primary full" onClick={() => { addToCart(selected); setSelected(null); }}>أضف إلى السلة <ShoppingBag size={17} /></button><button className="preview-button"><BookOpen size={16} /> اقرأ عينة مجانية</button></div></div></div>}
    {cartOpen && <div className="overlay" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><h2>سلة التسوق <span>({cart.length})</span></h2><button className="close-button" onClick={() => setCartOpen(false)}><X size={19} /></button></div>{cart.length ? <><div className="cart-items">{cart.map((book) => <div className="cart-item" key={book.id}><BookCover book={book} size="tiny" /><div><strong>{book.title}</strong><small>{book.author}</small><b>{book.price}</b></div><button onClick={() => setCart((items) => items.filter((item) => item.id !== book.id))}><X size={15} /></button></div>)}</div><div className="cart-total"><span>الإجمالي</span><strong>{cart.reduce((sum, book) => sum + Number(book.price.split(" ")[0]), 0)} ر.س</strong></div><button className="btn-primary full">إتمام الشراء <ArrowLeft size={17} /></button></> : <div className="empty-cart"><ShoppingBag size={36} /><p>سلتك تنتظر كتابك القادم.</p><button className="btn-ghost" onClick={() => setCartOpen(false)}>تصفح الكتب</button></div>}</aside></div>}
    {assistantOpen && <div className="overlay" onClick={() => setAssistantOpen(false)}><div className="assistant-modal" onClick={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setAssistantOpen(false)}><X size={19} /></button><div className="assistant-title"><span><Bot size={23} /></span><div><h2>مساعد رفوف الذكي</h2><small>جاهز ليساعدك في الاختيار</small></div></div><div className="assistant-chat"><div className="bot-message">مرحبًا! ما الموضوع الذي ترغب في القراءة عنه اليوم؟</div>{querySent && <><div className="user-message">أريد كتابًا يساعدني على تطوير مهارات القيادة</div><div className="bot-message">ترشيحي الأول لك هو <strong>ابدأ مشروعك الآن</strong> — عملي، واضح، ومناسب لبدايتك.</div></>}</div>{!querySent && <div className="assistant-suggestions"><button onClick={() => setQuerySent(true)}>تطوير مهارات القيادة</button><button onClick={() => setQuerySent(true)}>رواية ملهمة</button></div>}<div className="assistant-input"><input placeholder="اكتب ما تبحث عنه..." onKeyDown={(e) => e.key === "Enter" && setQuerySent(true)} /><button onClick={() => setQuerySent(true)}><Send size={17} /></button></div></div></div>}
  </main>;
}

function BookCover({ book, size, className = "" }: { book: Book; size: "tiny" | "small" | "medium" | "large"; className?: string }) { return <div className={`book-cover ${size} cover-${book.accent} ${className}`}><span className="cover-top">رفوف</span><div className="cover-shape"><BookOpen size={size === "large" ? 34 : 19} /></div><strong>{book.cover}</strong><small>{book.author}</small><span className="cover-bottom">كتاب يغيّر شيئًا</span></div>; }

function BookCard({ book, favorite, onFavorite, onCart, onOpen }: { book: Book; favorite: boolean; onFavorite: () => void; onCart: () => void; onOpen: () => void }) { return <article className="book-card"><div className="book-visual" onClick={onOpen}><BookCover book={book} size="medium" /><span className="book-badge">{book.badge}</span><button className={`favorite-button ${favorite ? "liked" : ""}`} onClick={(e) => { e.stopPropagation(); onFavorite(); }} aria-label="المفضلة"><Heart size={17} fill={favorite ? "currentColor" : "none"} /></button><button className="quick-preview" onClick={(e) => { e.stopPropagation(); onOpen(); }}><BookOpen size={15} /> معاينة</button></div><div className="book-info"><span className="book-category">{book.category}</span><h3>{book.title}</h3><p>{book.author}</p><div className="rating"><Star size={14} fill="currentColor" /> {book.rating} <span>({book.reviews})</span></div><div className="book-buy"><div><strong>{book.price}</strong><del>{book.oldPrice}</del></div><button className="add-cart" onClick={onCart}><ShoppingBag size={17} /></button></div></div></article>; }
